(defpackage :test-suite
  (:use lispyboi))

(in-package :test-suite)

(provide "test-suite")
(require "asserts")
(require "time-it")

(defun run-test (path)
  (format t "Running test: ~a~%" path)
  (load path))

(time-it test-time
         (progn
           (run-test "tests/test_aref.lisp")
           (run-test "tests/test_defgeneric.lisp")
           (run-test "tests/test_defpackage.lisp")
           (run-test "tests/test_defstruct.lisp")
           (run-test "tests/test_destructuring-bind.lisp")
           (run-test "tests/test_equal.lisp")
           (run-test "tests/test_format.lisp")
           (run-test "tests/test_handler-case.lisp")
           (run-test "tests/test_hash-table.lisp")
           (run-test "tests/test_lists.lisp")
           (run-test "tests/test_labels.lisp")
           (run-test "tests/test_math.lisp")
           (run-test "tests/test_parse.lisp")
           (run-test "tests/test_quasiquote.lisp")
           (run-test "tests/test_setf.lisp")
           (run-test "tests/test_stream.lisp")
           (run-test "tests/test_typep.lisp")
           (run-test "tests/test_unwind-protect.lisp")
           (run-test "tests/test_labels.lisp"))
         (format t "Tests completed in ~dms~%" test-time))
