(require "asserts")
(require "time-it")

(defun run-test (path)
  (print "Running test: ")
  (print-line path)
  (load path))

(time-it test-time
         (progn
           (run-test "test_equal.lisp")
           (run-test "test_math.lisp")
           (run-test "test_lists.lisp")
           (run-test "test_quasiquote.lisp")
           (run-test "test_handler-case.lisp"))
           (run-test "test_format.lisp"))
         (print "Tests completed in ")
         (print test-time)
         (print-line "ms."))

(provide "test-suite")
